kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount.culler }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccount.culler }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["*"]
    resourceNames: []
    verbs: ["create", "delete", "get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.culler }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.serviceAccount.culler }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.culler }}
    namespace: {{ .Values.namespace }}