# Default values for scheduled staging clean up.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: services

image:
  jobs:
    repository: ""
    pullPolicy: IfNotPresent
    imageName: scheduled-jobs-production
    tag: scheduled-staging_clean_up-0.2.0

environmentVariables:
  # - name: CLOUD_LIBRARY_VERSION
  #   value: 0.2.0
  # - name: COMPONENT_LIBRARY_VERSION
  #   value: 0.2.0
  # - name: DATAOP_LIBRARY_VERSION
  #   value: 0.2.0
  # - name: NETWORK_LIBRARY_VERSION
  #   value: 0.2.0
  # - name: PROTO_LIBRARY_VERSION
  #   value: 0.2.0

imagePullSecrets: []

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

schedule: '* * * * *'

nodeSelector:
  role: service

tolerations: []

affinity: {}

clusterId:
useKubeEnvironment: