apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.service.port }}
      protocol: TCP
      targetPort: {{ .Values.containerPort.service }}
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-gateway-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - name: http
      port: {{ .Values.containerPort.gateway }}
      protocol: TCP
      targetPort: {{ .Values.containerPort.gateway }}
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-load-balancer
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  ports:
    - name: http
      port: {{ .Values.service.gateway.port }}
      protocol: TCP
      targetPort: {{ .Values.containerPort.gateway }}
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer